defmodule Itsquitz.Repo.Migrations.CreateAnswers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:answer, primary_key: false) do
      add :answer, :text, null: false

      add :quiz_id,
          references(:quiz,
            column: :id,
            name: "answer_quiz_id_fkey",
            type: :uuid,
            prefix: "public"
          ), primary_key: true, null: false

      add :partecipant_id,
          references(:partecipant,
            column: :id,
            name: "answer_partecipant_id_fkey",
            type: :uuid,
            prefix: "public"
          ), primary_key: true, null: false
    end
  end

  def down do
    drop constraint(:answer, "answer_partecipant_id_fkey")

    drop constraint(:answer, "answer_quiz_id_fkey")

    drop table(:answer)
  end
end
