defmodule Itsquitz.Repo.Migrations.QuizNonNullableColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:quiz) do
      modify :text, :text, null: false
      modify :question1, :text, null: false
      modify :question2, :text, null: false
      modify :question3, :text, null: false
      modify :question4, :text, null: false
      modify :correct_answer, :text, null: false
      modify :argument, :text, null: false
      modify :points, :bigint, null: false
    end
  end

  def down do
    alter table(:quiz) do
      modify :points, :bigint, null: true
      modify :argument, :text, null: true
      modify :correct_answer, :text, null: true
      modify :question4, :text, null: true
      modify :question3, :text, null: true
      modify :question2, :text, null: true
      modify :question1, :text, null: true
      modify :text, :text, null: true
    end
  end
end
