defmodule Itsquitz.Repo.Migrations.CreateQuiz do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:quiz, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :text, :text
      add :question1, :text
      add :question2, :text
      add :question3, :text
      add :question4, :text
      add :correct_answer, :text
      add :argument, :text
      add :points, :bigint
    end
  end

  def down do
    drop table(:quiz)
  end
end
